name: Branch Preview

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            **/package-lock.json
      - name: Install dependencies
        run: |
          npm ci

      - name: Build and Deploy to Netlify
        run: |
          netlify deploy --prod --build

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
