name: Branch Preview Comment

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build & Deploy to Netlify
        run: netlify deploy --build --context deploy-preview --alias 'pr-review-${{ github.event.number }}'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_SITE_ID }}
          PR_NUMBER: ${{ github.event.number }}
      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            This pull request is being automatically deployed to Netlify.

            ✅ Preview: https://deploy-preview--stirring-maamoul-${{ env.PR_NUMBER }}.netlify.app
            🔖 Deployed version: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
