name: Branch Preview Comment

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to preview mode
        uses: thundermiracle/netlify-deploy@v3
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_SITE_ID}}
          install-command: npm ci
          build-command: npm run build
          cache-strategy: npm
          deploy-dir: '.next'
          production: false
          node: 18.18.0
