name: Branch Preview Comment

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - '*'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            **/package-lock.json

      - name: Install dependencies
        run: |
          npm ci

      - name: Build and Deploy to Netlify
        id: build-app
        run: |
          npm run build
          netlify deploy --build --prod

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_SITE_ID }}

      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OUTPUT: "This pull request is being automatically deployed to Netlify.\n\n✅ Preview: ${{ steps.build-app.outputs.deploy-url }}"
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false
